name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main # 仅在主干合并时触发生产级上架

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Inject Oryx Engine and Deploy Static Assets
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # 昨晚提取的真机 Token
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"

          # =========================================================================
          # 刚性目录定义：彻底明确前后端编译物理边界
          # =========================================================================
          app_location: "src/client-edge"          # 👈 前端 3D 门户所在目录
          api_location: "src/cloud-orchestrator"  # 🟩 激活：命令 GitHub 将后端塞进 SWA 内部
#          api_location: ""  # 🟩 绝杀置空：物理斩断内嵌函数繁衍，强迫网关释放 /api 路由主权
          output_location: ""